version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./vols/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./vols/nginx/conf.d:/etc/nginx/conf.d
      - ./vols/nginx/html:/usr/share/nginx/html
    networks:
      default:
        aliases:
          - id.foundry.local
          - topomojo.foundry.local

    depends_on:
      - topomojo
      - identity

  identity:
    image: cmusei/identity:1.3.0
    restart: unless-stopped
    entrypoint: ["bash", "/entry.d/entrypoint"]
    command: ["dotnet", "IdentityServer.dll"]
    environment:
      APPSETTINGS_PATH: /app/conf/identity.conf
    volumes:
      - ./vols/entry.d:/entry.d
      - ./vols/identity-conf:/app/conf
    depends_on:
      - postgres

  identity-ui:
    image: cmusei/identity-ui:1.3.0
    restart: unless-stopped
    volumes:
      - ./vols/identity-conf/identity-ui-settings.json:/var/www/ui/assets/settings.env.json

  appmail:
    image: cmusei/appmailrelay:2.3.0
    restart: unless-stopped
    environment:
      MAIL__HOST: ""
      MAIL__USER: ""
      MAIL__PASSWORD: ""
      MAIL__PORT: 25
      MAIL__SENDER: ""
      RELAY__CLIENTKEYS__0: id.foundry.local#321ChangeMe!

  topomojo:
    image: cmusei/topomojo:1.3.0
    restart: unless-stopped
    entrypoint: ["bash", "/entry.d/entrypoint"]
    command: ["dotnet", "TopoMojo.Web.dll"]
    volumes:
      - ./vols/entry.d:/entry.d
      - ./vols/topomojo-conf/topomojo.conf:/app/conf/appsettings.conf
      - topomojo-nfs:/mnt/tm
    depends_on:
      - postgres

  topomojo-ui:
    image: cmusei/topomojo-ui:1.3.0
    restart: unless-stopped
    volumes:
      - ./vols/topomojo-conf/topomojo-ui-settings.json:/var/www/assets/config/settings.json

  postgres:
    image: postgres:11.8
    environment:
      POSTGRES_PASSWORD: 321ChangeMe!
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  topomojo-nfs:
    # driver_opts:
    #   type: "nfs"
    #   o: "addr=<your nfs ip>,rw,nfsvers=4,async"
    #   device: ":<your export path>"
